### ISSUE TITLE
vagrant up is failed

### ISSUE THREAD

**Issue by nyasukun** [dmorrill10/acpc_poker_gui_client#94]
When invoke vagrant up, we got following error:

> $ vagrant up
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Box 'ubuntu-precise-32bit-vanilla' could not be found. Attempting to find and install...
>     default: Box Provider: virtualbox
>     default: Box Version: >= 0
> ==> default: Box file was not detected as metadata. Adding it directly...
> ==> default: Adding box 'ubuntu-precise-32bit-vanilla' (v0) for provider: virtualbox
>     default: Downloading: https://dl.dropboxusercontent.com/u/165709740/boxes/precise32-vanilla.box
> An error occurred while downloading the remote file. The error
> message, if any, is reproduced below. Please fix this error and try
> again.
> 
> The requested URL returned error: 404 Not Found

It seems dropbox site is gone.
Is it maintained?

**Comment by dmorrill10** [comment]
Sorry, the Vagrantfile hasn't been used by anyone in a long time. I tried to make a better setup with <https://github.com/dmorrill10/acpc_vagrant>, so maybe try this instead. I'm not using it right now either, but it has been updated more recently.

**Comment by nyasukun** [comment]
I got error message with acpc_vagrant project.
I will raise an issue to that project.
